### ISSUE TITLE
NonTemplatedInputDirException on template with static file names.

### ISSUE THREAD

**Issue by juanjoLenero** [audreyr/cookiecutter#1068]
* Cookiecutter version: 1.6.0
* Python version: 2.7
* Operating System: macOS High Sierra

### Description:

I'm trying to generate a template that creates a couple of test files for my project.

```
my-template/
--- cookiecutter.json
--- resolvers.test.js
--- test-fixtures.js
```

### What I've run:

```
// Inside dir where I want to create the test files.
cookiecutter /path/to/my-template
```
I get `cookiecutter.exceptions.NonTemplatedInputDirException`

```
Traceback (most recent call last):
  File "/usr/local/bin/cookiecutter", line 11, in <module>
    load_entry_point('cookiecutter==1.6.0', 'console_scripts', 'cookiecutter')()
  File "/usr/local/Cellar/cookiecutter/1.6.0/libexec/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/cookiecutter/1.6.0/libexec/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/cookiecutter/1.6.0/libexec/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Cellar/cookiecutter/1.6.0/libexec/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/cookiecutter/1.6.0/libexec/lib/python2.7/site-packages/cookiecutter/cli.py", line 120, in main
    password=os.environ.get('COOKIECUTTER_REPO_PASSWORD')
  File "/usr/local/Cellar/cookiecutter/1.6.0/libexec/lib/python2.7/site-packages/cookiecutter/main.py", line 94, in cookiecutter
    output_dir=output_dir
  File "/usr/local/Cellar/cookiecutter/1.6.0/libexec/lib/python2.7/site-packages/cookiecutter/generate.py", line 257, in generate_files
    template_dir = find_template(repo_dir)
  File "/usr/local/Cellar/cookiecutter/1.6.0/libexec/lib/python2.7/site-packages/cookiecutter/find.py", line 36, in find_template
    raise NonTemplatedInputDirException
cookiecutter.exceptions.NonTemplatedInputDirException
```
I believe this is because none of my template files use variables in their names, e.g. `{{cookiecutter.modelName}}-resolvers.test.js` is there a way to skip that requirement?

**Comment by vsoch** [comment]
I just got this error as well! Is there any updates on how to resolve it?

```bash
$ cookiecutter --version
Cookiecutter 1.6.0 from /home/vanessa/anaconda3/lib/python3.6/site-packages (Python 3.6)
```

**Comment by pydanny** [comment]
Apologies, but you are asking for a proven feature of Cookiecutter to be removed.

The design of Cookiecutter is for the template to have a top level directory to have template configuration files. For example, this means you can use continuous integration and `pytest-cookies` to confirm your project template isn't broken on a change. Reference [Cookiecutter Django's](https://github.com/pydanny/cookiecutter-django) root directory, including `tests` to see how this works in a real-world project.

So allowing top level files to be included in a generated template just isn't going to happen. It breaks the original architecture envisioned by @audreyr. Instead, you need to create a `{{cookiecutter.project_slug}}` or other similarly named directory for your project.

**Comment by vsoch** [comment]
thanks @pydanny ! I'm a new user and was able to figure this out - I just didn't know that the entire thing needed to be in a subfolder (I had the cookiecutter.json on the same level as a bunch of things). Once I put everything into a directory named by the slug, it worked. I am adding this note so others know my predicament (and solution) as well. The other challenge I ran into was having jinja2 files templated, and the solution was to add `{% raw %}` and `{% endraw %}` This is a great project!

**Comment by indrif** [comment]
But wait what? So I _have_ to use a templated root dir? What if I want cookiecutter to create a templated dir inside an existing dir, such as A/b/{{cookiecutter.slug_name}}? Is that really something that breaks the initial vision you mentioned earlier?

**Comment by pointtonull** [comment]
I don't see the point.
In which way does it make impossible to test?

Having to have a templated root does break some use cases, like using it to create dev files inside a pre-created repository. Forces me to hack around with hooks when it could easily (and safely) be handled by cookiecutter.

**Comment by cal97g** [comment]
Basically what nobody will actually come out and say is you need a directory structure like this:
```
 - template
      - cookiecutter.json
      - somefolder
            - filea.txt
      - some_file.py
```
Your cookiecutter.json needs to be in the template root

**Comment by Feuermurmel** [comment]
I ran into the same issue. Without commenting on whether `cookiecutter` should support this use case or not, this is the workaround I came up with. This template will add a `license.txt` to the current directory:

```
# cookiecutter.json
{}

# {{cookiecutter and '%'}}/license.txt
[the license]

# hooks/post_gen_project.sh
#! /usr/bin/env bash

set -eu
mv * ..
rm ../%
```

`%` is just used as the name of the directory created when the template is instantiated and removed later. Mind you that implemented like this, it will overwrite already existing files with the same name as in the template.

**Comment by hartleybrody** [comment]
Requiring the top-level of any cookiecutter template project to be devoid of anything except cookicutter config and a strangely named folder with curly braces is a poor decision and ultimately why I'm not using this project to template my flask boilerplate. The fact that this ticket has so many reacts and comments indicates many others are also confused by this design decision. 

The only official comment from the project team on the issue seems to say that this is somehow a "proven feature" and changes to this decision "aren't going to happen" which comes off as an arrogant dismissal of people who are trying to figure out how to make the best use of this tool for their projects.

IMO, a more sensible way to namespace those things would be to create a single `.cookiecutter` directory at the top of the project that could be tucked neatly in with the rest of the application logic, instead of swallowing everything up. Not sure if there's any appetite among the core team to make a change like that, or if they're still sticking to their guns on this issue.

**Comment by Feuermurmel** [comment]
@hartleybrody

> The only official comment from the project team on the issue seems to say that this is somehow a "proven feature" and changes to this decision "aren't going to happen" which comes off as an arrogant dismissal of people who are trying to figure out how to make the best use of this tool for their projects.

I think the developers just have a different opinion on that technical decision. I don't think they set out to hurt anyone's feelings by communicating it.

**Comment by bittner** [comment]
**Disclaimer:** _This comment is meant for people looking for an immediate solution. I don't intend to bash this project or offend anyone here._

An alternative scaffolding tool that doesn't have this – apparently arbitrary – restriction is [Copier](https://github.com/copier-org/copier).

(Also, it has a YAML configuration file and doesn't use a prefix for template variables, which I personally find neat, because it makes the template code nicely readable.)

I had to use it on a project that sports [3 templates from a single repository](https://github.com/painless-software/python-cli-test-helpers/tree/main/examples).

**Comment by hydrargyrum** [comment]
A bit late to the party but I found a partial workaround:

Have this hierarchy tree:

```
my-template/
- cookiecutter.json
- {{'.' or cookiecutter.whatever}}/
  - resolvers.test.js
  -  test-fixtures.js
```

(Yes, the dir must be named `{{'.' or cookiecutter.whatever}}`)
then run cookiecutter with `-f` option, it will try to create files in directory `.`, that is, current directory, what we want and cookiecutter is happy because it believes the directory is templated

**Comment by kylebeni** [comment]
Sharing a simple solution that worked for me:

- my_template
  - `{{cookiecutter.__folder_name}}`
    - `file_a.js`
    - `file_b.js`
  - `cookiecutter.json`

In `cookiecutter.json`:
```json
{
"__folder_name": "static_folder_name"
{
```
