### ISSUE TITLE
Conditional files / directories

### ISSUE THREAD

**Issue by mgaitan** [audreyr/cookiecutter#127]
This is a complement issue for #126. Sometimes I want to create a file only under certain condition. 

I propose that the function `generate_file()` ignores the creation of file if its filename is empty. So, for example, I could template a filename like this :

``` jinja
/{% if cookiecutter.some_var %}{{ cookiecutter.another }}.txt{% endif %}
```
It seems this logic actually works for directories, but not for files.

**Comment by nichochar** [comment]
I would love this. I hadn't found this ticket so posted it on SO: http://stackoverflow.com/questions/35005098/can-i-make-a-file-optional-based-on-a-variables-value-in-cookiecutter-json/35020626#35020626

**Comment by glenfant** [comment]
Got a use case where I need a `__main__.py` if there's a console_script entry point in `setup.py`. Otherwise (pure lib) I don't need such file.

**Comment by pydanny** [comment]
This can be done in post-generate hooks as seen in https://github.com/pydanny/cookiecutter-django/blob/master/hooks/post_gen_project.py#L163-L165. This makes this issue more an education issue then a technical solution. This is good because making logic work in directory/file names on Windows is impossible (and we support Windows).

Therefore, I believe this is better done as a recipe described in the [advanced_usage.rst](https://github.com/audreyr/cookiecutter/blob/master/docs/advanced_usage.rst) document.
