### ISSUE TITLE
Allow specifying a directory where `cookiecutter.json` resides

### ISSUE THREAD

**Issue by oz123** [audreyr/cookiecutter#462]
I would like to checkout github repository for using with cookiecutter, where `cookiecutter.json` does not reside at the top level. 

e.g.
```
cookiecutter('https://github.com/oz123/myrepo.git')
....
IOError: [Errno 2] No such file or directory: u'/home/oti/.cookiecutters/myrepo/cookiecutter.json'
```
This happens because cookiecutter.json resides inside `plugin-template`. 

A simple solution would be to allow another parameter to cookiecutter, e.g. instead of the following signature:
```
def cookiecutter(input_dir, checkout=None, no_input=False, extra_context=None):
```
Use:
```
def cookiecutter(input_dir, checkout=None, no_input=False, extra_context=None, context_file_dir=None):
```

This requires changing how `context_file` is set:
Instead of:
```
context_file = os.path.join(repo_dir, 'cookiecutter.json') 
```
Context file is now determined like this:
```
if context_file_dir:
      context_file = os.path.join(repo_dir,context_file_dir, 'cookiecutter.json') 
else: 
      context_file = os.path.join(repo_dir, 'cookiecutter.json') 
```

**Comment by hackebrot** [comment]
Hi @oz123! Thank you for submitting an issue to *Cookiecutter*.

IMHO this is a tough one. Implementation-wise it is totally possible. No doubt about that.

However I feel that the user shouldn't be the one to figure out where ``cookiecutter.json`` is located, because he doesn't necessarily needs to know that *Cookiecutter* is looking for it. From my experience it is always a balancing act between bloating a tool out and keeping its original concept of being a utility.

I am very open to a discussion though... :bow:

**Comment by pydanny** [comment]
:-1: 

I'm very much opposed to specifying the location of `cookiecutter.json`. Having it at the root of the repo means that it's trivial to identify cookiecutter templates. If someone does want to use a non-standard location for their `cookiecutter.json`, they can just do:

```
git clone gh:github.com/oz123/myrepo
cd myrepo
cookiecutter plugin-template
```

Furthermore, one could use components of cookiecutter's internal API to automate much of this in a script. There are functions that:

1. Clone repo
2. Change directory context
3. Runs cookiecutter against a local directory

FWIW, there are shops that write scripts that perfect exactly this action.
