### ISSUE TITLE
Create multiple files from list

### ISSUE THREAD

**Issue by theiviaxx** [audreyr/cookiecutter#474]
I wasn't able to find this, but i'd like to define a list in the context and then create files based on the loop.  I guess a potential syntax could be:

    files{% for name in cookiecutter.name %}
        {{name}}.txt

So the folder name would be the loop declaration and the files inside would be generated per loop

cookiecutter.json

    {
        "names": ["foo", "bar"
    }

would yield

    files
        foo.txt
        bar.txt

Might be a little too complicated, but figured i would ask.  Or if there is interest i can do a pull request

**Comment by hackebrot** [comment]
Thank you for filing an issue @theiviaxx!

If I am not mistaken the proposed solution wouldn't work with our implementation for choices. However I have been thinking about this before. Feel like we should investigate and agree on a concept first.

Please see https://github.com/audreyr/cookiecutter/blob/master/cookiecutter/prompt.py#L119

**Comment by pydanny** [comment]
Closing this as it can be done in both the `pre_generate` and `post_generate` hooks.

**Comment by avanov** [comment]
Where can I find a docs section that demonstrates this functionality?

**Comment by cjolowicz** [comment]
@avanov There are really two separate questions here.

Generating files can be done using a `post_generate` hook, which is documented [here](https://cookiecutter.readthedocs.io/en/1.7.2/advanced/hooks.html).

A variable with a list value is not possible, because lists are how choices are implemented. (After the choice is presented to the user, the list is replaced with the chosen value.) However, you can have lists nested in dicts. This is documented in the section about [Dictionary variables](https://cookiecutter.readthedocs.io/en/1.7.2/advanced/dict_variables.html).

**Comment by amit-disc** [comment]
Hi, i tried to generate some files with post hook but it fails to find the directory. 
No such file or directory
ERROR: Stopping generation because post_gen_project hook script didn't exit successfully

It is not able to find the generate directory and fails. I though that post hook runs after the directory has been generated from the template
