### ISSUE TITLE
fail_if_exists not used

### ISSUE THREAD

**Issue by schacki** [audreyr/cookiecutter#475]
Based on the discussion in #471  and #470  and based on the code, I understand that this should be optional and the behavior should be controlled by the boolean variable "fail_if_exists". However, "fail_if_exists" is currently hardcoded to True in the call to render_and_create_dir. At the same time, the default value in render_and_create_dir is set to False. This seems contradictory and not intended.
In my view the behavior should be controllable by the user, e.g. via command line argument.

**Comment by hackebrot** [comment]
cc @lgp171188

**Comment by lgp171188** [comment]
@schacki @hackebrot The reason why I chose the default for ``fail_if_exists`` as ``False`` and overrode in one particular place is to keep other code which depend on the previous behaviour of render_and_create_dir from breaking. It looks to be a bad choice.

One way to fix it is to toggle the default and explicitly make ``fail_if_exists`` to be ``False`` wherever required.

As for the command-line argument, we can have ``fail_if_exists=True`` as the default behaviour (since it is never good to automatically overwrite some thing that already exists) and we can expose a command-line flag, say ``--overwrite-if-exists`` which will allow the user to override it.

Please let me know your thoughts on this.

**Comment by hackebrot** [comment]
cc @pydanny @michaeljoseph

**Comment by hackebrot** [comment]
:bell:
