### ISSUE TITLE
Subdirectories

### ISSUE THREAD

**Issue by skhaz** [audreyr/cookiecutter#545]
Hi,

I need to deal with subdirectories for an Android project, e.g.: `com/foobar/appname/activity`, I knew that jinja2 have for statement, can I use this for create the subdirectories?

**Comment by hackebrot** [comment]
Hi @skhaz, could you please provide us with a more detailed example of what you are trying to accomplish? Thanks :bow:

**Comment by hackebrot** [comment]
:bell:

**Comment by pydanny** [comment]
Jinja2 `{% for %}` loops work with directories, but doing recursion of subdirectories won't work.  `{% for %}` will break on Windows, because of the way their OS works, which is why we don't recommend adding logic to file/directory names in Cookiecutter templates.

That said, the better way of handling creation of subdirectories:

1. Via `post_gen_hooks`. Then you can write Python to create the subdirectories. However, then the Cookiecutter evaluation doesn't occur there.
2. By calling the internal Cookiecutter API from your own script. This is the way I would go. It's not documented well as of yet, but it's powerful.

I'm closing this as @skhaz hasn't responded and this is resolved by my second solution.
