### ISSUE TITLE
Date format

### ISSUE THREAD

**Issue by cameron707** [audreyr/cookiecutter#699]
It's not at all obvious as to the format of the date when running a cookiecutter and setting it up.

Eg: 2016-2-1 doesn't indicate in which position the month and day are. It would be more helpful for the user to give a default value more like 2016-1-31 which would make it obvious, or better still it would be more idiot-proof if the format was displayed regardless of how the author decides to create his/her cookiecutter.

**Comment by hackebrot** [comment]
Hey @cameron707! 👋 

Are you sure you are in the right issue tracker? Cookiecutter itself doesn't create any dates by itself. There is support for dates in templates via [jinja2-time](https://github.com/hackebrot/jinja2-time), but it's up to the template author to make use of it and the format for date and times is fully configurable.

If you could provide us with a little bit more information on what you are trying to do?

**Comment by cameron707** [comment]
Well I'm very new to all of this and the few cookiecutters that I've seen have not been clear on what the date format is. Perhaps it's common knowledge in the django community as to what format the date is normally in, I don't know. I just thought I'd offer my perspective from someone that's just starting. Since the design principle is in essence to make life easier it would make a lot of sense to strictly enforce displaying the date format. I see it as one of those things I'll have to look up every time unnecessarily. It's a small issue but I guess if I can run a cookiecutter and generate a project without looking stuff up then there is a kind of beauty in that.

**Comment by michaeljoseph** [comment]
@cameron707, as @hackebrot said, we don't really have the ability to intercept and enforce formatting on `datetime` fields, so I'd suggest filing an issue with the cookiecutter template you're using and either:
- request an unambigous default for their `datetime` field
- ask them to use [jinja2-time](https://github.com/hackebrot/jinja2-time) (since the most common use-case of `datetime` fields is incorporating the current datetime)
