### ISSUE TITLE
Wrong hook executed when a tilde-suffixed file of the same name exists

### ISSUE THREAD

**Issue by amPerl** [audreyr/cookiecutter#767]
* Cookiecutter version: 1.4.0
* Template project url: https://github.com/thorgate/django-project-template
* Python version: 3.4
* Operating System: Ubuntu 15.10 wily

### Description:

When using gedit or some other text editor that pollutes the directory with backup files ending with a tilde, cookiecutter mistakes that for the "real" hook it should run. This resulted in cookiecutter running a ridiculously outdated version of my pre-gen hook.

The obvious solution is to just remove `pre_gen_project.py~`, which works, but I believe ideally cookiecutter shouldn't be running it in the first place.

### What I've run:

```
gedit django-template/hooks/pre_gen_project.py
cookiecutter django-template
```

**Comment by pfmoore** [comment]
The problem is that cookiecutter treats any file with a basename of ```pre_gen_project``` as a hook. If it has extension ```.py``` it runs it via Python, but otherwise it just lets the OS run it. This allows for Windows to use hooks with extensions ```.bat```, ```.cmd```, ```.ps1```, etc, as well as letting Unix users add extensions like ```.sh```, or ```.rb``` (with a suitable shebang).

It's hard to know what extensions should be disallowed. Maybe skip any files with names ending in ```~``` as that's a common convention for old backup files?

**Comment by amPerl** [comment]
That's what I also thought should be done. I also forked and wrote a quick patch for it, but I read the PR guide and apparently you need tests and whatnot, which I currently don't have the time to write.

**Comment by hackebrot** [comment]
Hi @amPerl, thanks for submitting an issue! 🙇 

> tests and whatnot

If you need help on how to write tests for Cookiecutter, let me know. Not sure what "whatnot" is supposed to mean. 😉 

Please review #768.

**Comment by amPerl** [comment]
Awesome! Thanks for the swift fix.
