### ISSUE TITLE
pre_gen hook doesn't appear to be loading custom extensions

### ISSUE THREAD

**Issue by cheungnj** [audreyr/cookiecutter#850]
Latest version of cookiecutter from master. Last commit [ceafa1dc1b5eb70835ffba5dc7457df269d77ba8](https://github.com/audreyr/cookiecutter/commit/ceafa1dc1b5eb70835ffba5dc7457df269d77ba8)

In my pre_gen_project hook, I have this code: `{{cookiecutter.should_be_list | to_sequence}}` which turns a string into a list but cookiecutter raises a TemplateAssertionError `jinja2.exceptions.TemplateAssertionError: no filter named 'to_sequence'`. I know that my to_sequence filter isn't the issue because when I use it in other parts of my template and remove it from the pre_gen hook, everything executes successfully.

Are the custom extensions intended to only be loaded after the pre_gen hook is finished executing?

**Comment by michaeljoseph** [comment]
Hi @cheungnj,

Thanks for the issue!

This looks like an oversight, we should be using the same Jinja environment to render hooks as we do elsewhere.
This looks like a relatively easy fix to implement- would you like to submit a PR?

Essentially, we should be using [cookiecutter.environment.StrictEnvironment](https://github.com/audreyr/cookiecutter/blob/master/cookiecutter/generate.py#L253) instead of just [jinja2.Template](https://github.com/audreyr/cookiecutter/blob/master/cookiecutter/hooks.py#L94) in `cookiecutter.hooks.run_script_with_context`.

**Comment by hackebrot** [comment]
Hey @cheungnj! 👋 

I've just pushed a PR adding two tests that replicate this bug. As @michaeljoseph said, we would happily review a PR from you to address this issue, feel free to base your branch off of #856.

Please let us know in case of any questions!

**Comment by cheungnj** [comment]
@michaeljoseph @hackebrot 

I'd be happy to submit a PR for this. Thanks for the opportunity to contribute!

**Comment by hackebrot** [comment]
Hey @cheungnj! 👋 

FYI The tests have been merged into master!
