### ISSUE TITLE
Conditional follow-up questions based on prior answers

### ISSUE THREAD

**Issue by coreysnyder04** [audreyr/cookiecutter#913]
* Cookiecutter version: Cookiecutter 1.5.1
* Python version: Python 3.6.0
* Operating System: OSX

### Description:
Is it possible to do conditional follow-up questions based on responses to previous questions? For instance:
Is there an empty repository created for this new project?  Yes
What is the repository URL?
Would you like us to auto-push to this Repo?

Where if you said **No** to the first question, it skips the next two.

**Comment by pydanny** [comment]
No. As much as we would like to incorporate this functionality into Cookiecutter, it's a lot of work to not just implement, but review across all platforms. We've yet to get any official sponsorship, which is what one of the maintainers would need in order to see this feature (and one of the pull requests for it) implemented.

What you can do for now is implement this behavior in a posthook. It requires some python coding to make it happen, but it's something you can find in some sophisticated projects like Cookiecutter Django.

**Comment by paveldedik** [comment]
Hi @pydanny I checked the code and it doesn't seem that hard to implement, I would probably do it here: https://github.com/cookiecutter/cookiecutter/blob/master/cookiecutter/prompt.py#L200-L222

We would just have to figure out the syntax for specifying conditional follow-up questions and also write it in a way so that it's not conflicting with dictionary variables or something else (probably use `_` as prefix for definition of conditional questions I guess?). Example:

```json
{
  "use_redis": "y",
  "_if_use_redis_y": {
    "redis_port": "6379",
    "use_hiredis": "y"
}
```

If that's all what is needed, I could implement it myself and send PR.

But I guess there are other issues which make this approach bad?

**Comment by jolo-dev** [comment]
Hi @paveldedik 
Have you done a PR?
Best

**Comment by max-k** [comment]
@paveldedik any news on this ?

**Comment by paveldedik** [comment]
Hi @jolo-dev and @max-k I didn't get any response from @pydanny if I recall correctly (if the solution is good and worth it), I also remember that when I needed it, I ended up using hooks which was good enough solution for me.

Sorry guys, I didn't work on this.

**Comment by jolo-dev** [comment]
Yes, in the end, I also used post hooks.
An example you can find here:
https://github.com/jolo-dev/cloud-bakery/blob/master/hooks/post_gen_project.py

**Comment by nilsdebruin** [comment]
> Hi @pydanny I checked the code and it doesn't seem that hard to implement, I would probably do it here: https://github.com/cookiecutter/cookiecutter/blob/master/cookiecutter/prompt.py#L200-L222
> 
> We would just have to figure out the syntax for specifying conditional follow-up questions and also write it in a way so that it's not conflicting with dictionary variables or something else (probably use `_` as prefix for definition of conditional questions I guess?). Example:
> 
> ```json
> {
>   "use_redis": "y",
>   "_if_use_redis_y": {
>     "redis_port": "6379",
>     "use_hiredis": "y"
> }
> ```
> 
> If that's all what is needed, I could implement it myself and send PR.
> 
> But I guess there are other issues which make this approach bad?

Based on the suggestion of @paveldedik I created a pull request to solve this (as I needed something like this for myself), see: https://github.com/cookiecutter/cookiecutter/pull/1645 . Hopefully this can be used!
